name: Star Playlist Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # ✅ har 30 min

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python script.py

      - name: Commit Playlist
        run: |
          git config --global user.name "rkdyiptv"
          git config --global user.email "rk@github.com"
          git add .
          git commit -m "Auto Update Playlist" || echo "No changes"
          git push
